title: Home
subtitle: Welcome to Vaios' personal website !
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website based on the jekyll template devlopr-jekyll.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Resume
      url: /resume
    - text: Publications
      url: /publications
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery

scholar:
  last_name: Vaios
  first_name: Papaspyros

  style: ieee
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: bibliography.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

author_logo: profile.jpeg
author: Vaios
# author_bio: Hi, my name is Vaios Papaspyros.
author_email: "b.papaspyros@gmail.com"
author_academic_email: "vaios.papaspyros@epfl.ch"
author_location: Lausanne, Switzerland
author_website_url: "bpapaspyros.github.io"
author_academic_page_url: "https://people.epfl.ch/vaios.papaspyros"
typewrite-text: Doctoral Assistant @ EPFL | Robotics, Machine Learning, Collective behaviour

full_cv_path: docs/VaiosPapaspyros.pdf

author_work_experiences:
            - company_name: École polytechnique fédérale de Lausanne (EPFL)
              company_logo: logos/logo_epfl.png
              company_url: https://www.epfl.ch/en/
              designation: Doctoral Assistant
              description:  
                "<b>Team:</b> Mobots @ Biorobotics laboratory (Biorob). </br>
                 <b>Research Topic:</b> Self-Adaptive Mixed Societies of Animals and Robots. </br>
                 <b>Thesis director:</b> Francesco Mondada. </br>
                 <b>Funding:</b> Swiss National Science Formation (SNF)."
              visibility: true
            - company_name: École polytechnique fédérale de Lausanne (EPFL)
              company_logo: logos/logo_epfl.png
              company_url: https://www.epfl.ch/en/
              designation: Research Intern
              description:  
                "<b>Team:</b> Mobots @ Laboratoire de Systèmes Robotiques (LSRO). </br>
                 <b>Research Topic:</b> Self-Adaptive Mixed Societies of Animals and Robots. </br>
                 <b>Supervisors:</b> Frank Bonnet, Francesco Mondada."
              visibility: true
            - company_name: University of Patras | Department of Mechanical Engineering & Aeronautics
              company_logo: logos/logo-upatras.png
              company_url: http://www.upatras.gr/en
              designation: Research Engineer
              description:  
                "<b>Team:</b> EuroSWARM team @ Applied Mechanics Lab. </br>
                 <b>Research Topic:</b> Unmanned Heterogeneous Swarm of Sensor Platforms. </br>
                 <b>Funding:</b> European Defense Agency (EDA) <a href=https://euroswarm.wordpress.com/>EuroSWARM Project</a>."
              visibility: true
            - company_name: National Institute for Research in Digital Science and Technology (Inria)
              company_logo: logos/logo-inria.png
              company_url: https://www.inria.fr/en
              designation: Research Intern
              description:  
                "<b>Team:</b> LARSEN/Resibots. </br>
                 <b>Internship Title:</b> Intelligent Trial & Error with the iCub humanoid robot. </br>
                 <b>Research Topic:</b> Robot damage recovery with safety constraints. </br>
                 <b>Supervisor:</b> Jean-Baptiste Mouret. </br>
                 <b>Funding:</b> European Research Council (ERC) <a href=https://resibots.eu/>ResiBots Project</a>."
              visibility: true

author_teaching_experiences:
            - year: 2020
              semester: Fall
              duties: Teaching Assistant
              workload: 2h/week
              course: Basics of Monile Robotics
              course_id: MICRO-452
              college_logo: logos/logo_epfl.png
              college_name: École polytechnique fédérale de Lausanne (EPFL)
              course_url: https://edu.epfl.ch/coursebook/en/basics-of-mobile-robotics-MICRO-452
              visibility: true
            - year: 2020
              semester: Spring
              duties: Teaching Assistant, Designer/Maintainer of the course
              workload: 4h/week
              course: Robot Operating System (ROS) basics
              course_id: MICRO-453
              college_logo: logos/logo_epfl.png
              college_name: École polytechnique fédérale de Lausanne (EPFL)
              course_url: https://edu.epfl.ch/coursebook/fr/robotics-practicals-MICRO-453
              visibility: true
            - year: 2019
              semester: Fall
              course_url: https://edu.epfl.ch/coursebook/en/basics-of-mobile-robotics-MICRO-452
              duties: Teaching Assistant
              workload: 2h/week
              course: Basics of Monile Robotics
              course_id: MICRO-452
              college_logo: logos/logo_epfl.png
              college_name: École polytechnique fédérale de Lausanne (EPFL)
              visibility: true
            - year: 2019
              duties: Teaching Assistant, Designer/Maintainer of the course
              semester: Spring
              workload: 4h/week
              course: Robot Operating System (ROS) basics
              duties: Teaching Assistant, Designer/Maintainer of the course
              course_id: MICRO-453
              college_logo: logos/logo_epfl.png
              college_name: École polytechnique fédérale de Lausanne (EPFL)
              course_url: https://edu.epfl.ch/coursebook/fr/robotics-practicals-MICRO-453
              visibility: true


author_education_details:
              - college_logo: logos/logo_epfl.png
                college_name: École polytechnique fédérale de Lausanne (EPFL)
                college_url: https://www.epfl.ch/en/
                college_degree: Doctor of Philosophy (PhD)
                description: Robotics, Control, and Intelligent Systems
                visibility: true
              - college_logo: logos/logo-upatras.png
                college_name: University of Patras
                college_url: https://www.ceid.upatras.gr/en
                college_degree: Dipl. Eng.
                description: Computer Engineering & Informatics
                visibility: true
              - college_logo: logos/logo-cgs.png
                college_name: Costeas-Geitonas School
                college_url: https://cgs.gr/en
                college_degree: High School
                visibility: true

author_project_details:
              - 
                # project_thumbnail: gamershub.png
                project_title: robot_dart
                project_description: I am a co-author of robot_dart, a flexible and generic C++11 wrapper for DART and is suitable for evolutionary computation.
                project_url: https://github.com/resibots/robot_dart
                visibility: true
              - 
                project_thumbnail: logo_limbo.png
                project_title: limbo
                project_description: I am a contributor to limbo, a highly templated C++11 Bayesian optimization framework.
                project_url: https://github.com/resibots/limbo
                visibility: true
contact_info:
              - telephone:
                  - work: +41 21 693 56 80 
                    personal: +41 78 860 11 13
                    visibility: true

              - postal_info:
                  - address: "EPFL STI IBI-STI </br>
                              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BIOROB </br> 
                              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=https://plan.epfl.ch/?room==ME%20B3%2030>ME B3 30</a> 
                              (Bâtiment ME) </br> 
                              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Station 9 </br>
                              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CH-1015 Lausanne</br>
                              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Switzerland"
                    visibility: true
author_interests:
              - cols:
                    - col1: "Collective Behaviour, Programming & design patterns, Robotcs"
                      col2: "Basketball, Music, Photography"
                visibility: true

twitter_username: bpapaspyros
github_username:  bpapaspyros
linkedin_username: bpapaspyros
instagram_username: vpapaspy
scholar_username: 4CCqmEUAAAAJ&hl=en
orcid_username: 0000-0001-8257-1891

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: vpapaspy

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
# formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_interests: true
show_full_cv_download: true
show_author_teaching_experiences: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
# collections:
#  - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
